name: Rust CI

on:
  push:
    branches: [ "main", "Develop" ]
  pull_request:
    branches: [ "main", "Develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-release:
    name: Test, Build & Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev pkg-config libgtk-3-dev libasound2-dev libxcb-shape0-dev libxcb-xfixes0-dev

    - name: Restore Certificate
      run: echo "${{ secrets.BINDKEY_CERT_BASE64 }}" | base64 -d > bindkey_cert.pem

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Check Formatting
      run: cargo fmt --all -- --check

    - name: Clippy (Linting)
      run: cargo clippy 

    - name: Install cargo-audit
      run: cargo install cargo-audit
      
    - name: Run Security Audit
      run: cargo audit

    - name: Run tests
      run: cargo test --verbose

    - name: Build Release
      run: cargo build --release --verbose

    - name: Prepare Package
      run: |
        mkdir release_package
        
        cp target/release/bindkey-software release_package/bindkey-client
        
        cp server_ip.txt release_package/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: bindkey-linux-package 
        path: release_package/      
        retention-days: 7
